# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_common.proto',
  package='message_common',
  serialized_pb=_b('\n\x14message_common.proto\x12\x0emessage_common\"+\n\x07\x44irInfo\x12\x0f\n\x07version\x18\x01 \x01(\x0c\x12\x0f\n\x07patches\x18\x02 \x01(\x0c\"5\n\x07Message\x12\x14\n\x0cmessage_name\x18\x01 \x01(\t\x12\x14\n\x0cmessage_body\x18\x02 \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DIRINFO = _descriptor.Descriptor(
  name='DirInfo',
  full_name='message_common.DirInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='message_common.DirInfo.version', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='patches', full_name='message_common.DirInfo.patches', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=83,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='message_common.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_name', full_name='message_common.Message.message_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_body', full_name='message_common.Message.message_body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['DirInfo'] = _DIRINFO
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE

DirInfo = _reflection.GeneratedProtocolMessageType('DirInfo', (_message.Message,), dict(
  DESCRIPTOR = _DIRINFO,
  __module__ = 'message_common_pb2'
  # @@protoc_insertion_point(class_scope:message_common.DirInfo)
  ))
_sym_db.RegisterMessage(DirInfo)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'message_common_pb2'
  # @@protoc_insertion_point(class_scope:message_common.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
