-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('message_common_pb')


local DIRINFO = protobuf.Descriptor();
local DIRINFO_VERSION_FIELD = protobuf.FieldDescriptor();
local MESSAGE = protobuf.Descriptor();
local MESSAGE_MESSAGE_NAME_FIELD = protobuf.FieldDescriptor();
local MESSAGE_MESSAGE_BODY_FIELD = protobuf.FieldDescriptor();


DIRINFO_VERSION_FIELD.name = "version"
DIRINFO_VERSION_FIELD.full_name = "message_common.DirInfo.version"
DIRINFO_VERSION_FIELD.number = 1
DIRINFO_VERSION_FIELD.index = 0
DIRINFO_VERSION_FIELD.label = 1
DIRINFO_VERSION_FIELD.has_default_value = false
DIRINFO_VERSION_FIELD.default_value = ""
DIRINFO_VERSION_FIELD.type = 12
DIRINFO_VERSION_FIELD.cpp_type = 9

DIRINFO.name = "DirInfo"
DIRINFO.full_name = "message_common.DirInfo"
DIRINFO.nested_types = {}
DIRINFO.enum_types = {}
DIRINFO.fields = {DIRINFO_VERSION_FIELD}
DIRINFO.is_extendable = false
DIRINFO.extensions = {}
MESSAGE_MESSAGE_NAME_FIELD.name = "message_name"
MESSAGE_MESSAGE_NAME_FIELD.full_name = "message_common.Message.message_name"
MESSAGE_MESSAGE_NAME_FIELD.number = 1
MESSAGE_MESSAGE_NAME_FIELD.index = 0
MESSAGE_MESSAGE_NAME_FIELD.label = 1
MESSAGE_MESSAGE_NAME_FIELD.has_default_value = false
MESSAGE_MESSAGE_NAME_FIELD.default_value = ""
MESSAGE_MESSAGE_NAME_FIELD.type = 9
MESSAGE_MESSAGE_NAME_FIELD.cpp_type = 9

MESSAGE_MESSAGE_BODY_FIELD.name = "message_body"
MESSAGE_MESSAGE_BODY_FIELD.full_name = "message_common.Message.message_body"
MESSAGE_MESSAGE_BODY_FIELD.number = 2
MESSAGE_MESSAGE_BODY_FIELD.index = 1
MESSAGE_MESSAGE_BODY_FIELD.label = 1
MESSAGE_MESSAGE_BODY_FIELD.has_default_value = false
MESSAGE_MESSAGE_BODY_FIELD.default_value = ""
MESSAGE_MESSAGE_BODY_FIELD.type = 12
MESSAGE_MESSAGE_BODY_FIELD.cpp_type = 9

MESSAGE.name = "Message"
MESSAGE.full_name = "message_common.Message"
MESSAGE.nested_types = {}
MESSAGE.enum_types = {}
MESSAGE.fields = {MESSAGE_MESSAGE_NAME_FIELD, MESSAGE_MESSAGE_BODY_FIELD}
MESSAGE.is_extendable = false
MESSAGE.extensions = {}

DirInfo = protobuf.Message(DIRINFO)
Message = protobuf.Message(MESSAGE)

