-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local message_common_pb = require("message_common_pb")
module('message_client_pb')


local TESTMESSAGE = protobuf.Descriptor();
local TESTMESSAGE_ID_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE_BUFF_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE2 = protobuf.Descriptor();
local TESTMESSAGE2_ID_FIELD = protobuf.FieldDescriptor();
local TESTMESSAGE2_BUFF_FIELD = protobuf.FieldDescriptor();


TESTMESSAGE_ID_FIELD.name = "id"
TESTMESSAGE_ID_FIELD.full_name = "message_client.TestMessage.id"
TESTMESSAGE_ID_FIELD.number = 1
TESTMESSAGE_ID_FIELD.index = 0
TESTMESSAGE_ID_FIELD.label = 1
TESTMESSAGE_ID_FIELD.has_default_value = false
TESTMESSAGE_ID_FIELD.default_value = 0
TESTMESSAGE_ID_FIELD.type = 5
TESTMESSAGE_ID_FIELD.cpp_type = 1

TESTMESSAGE_BUFF_FIELD.name = "buff"
TESTMESSAGE_BUFF_FIELD.full_name = "message_client.TestMessage.buff"
TESTMESSAGE_BUFF_FIELD.number = 2
TESTMESSAGE_BUFF_FIELD.index = 1
TESTMESSAGE_BUFF_FIELD.label = 1
TESTMESSAGE_BUFF_FIELD.has_default_value = false
TESTMESSAGE_BUFF_FIELD.default_value = ""
TESTMESSAGE_BUFF_FIELD.type = 12
TESTMESSAGE_BUFF_FIELD.cpp_type = 9

TESTMESSAGE.name = "TestMessage"
TESTMESSAGE.full_name = "message_client.TestMessage"
TESTMESSAGE.nested_types = {}
TESTMESSAGE.enum_types = {}
TESTMESSAGE.fields = {TESTMESSAGE_ID_FIELD, TESTMESSAGE_BUFF_FIELD}
TESTMESSAGE.is_extendable = false
TESTMESSAGE.extensions = {}
TESTMESSAGE2_ID_FIELD.name = "id"
TESTMESSAGE2_ID_FIELD.full_name = "message_client.TestMessage2.id"
TESTMESSAGE2_ID_FIELD.number = 1
TESTMESSAGE2_ID_FIELD.index = 0
TESTMESSAGE2_ID_FIELD.label = 1
TESTMESSAGE2_ID_FIELD.has_default_value = false
TESTMESSAGE2_ID_FIELD.default_value = 0
TESTMESSAGE2_ID_FIELD.type = 5
TESTMESSAGE2_ID_FIELD.cpp_type = 1

TESTMESSAGE2_BUFF_FIELD.name = "buff"
TESTMESSAGE2_BUFF_FIELD.full_name = "message_client.TestMessage2.buff"
TESTMESSAGE2_BUFF_FIELD.number = 2
TESTMESSAGE2_BUFF_FIELD.index = 1
TESTMESSAGE2_BUFF_FIELD.label = 1
TESTMESSAGE2_BUFF_FIELD.has_default_value = false
TESTMESSAGE2_BUFF_FIELD.default_value = ""
TESTMESSAGE2_BUFF_FIELD.type = 12
TESTMESSAGE2_BUFF_FIELD.cpp_type = 9

TESTMESSAGE2.name = "TestMessage2"
TESTMESSAGE2.full_name = "message_client.TestMessage2"
TESTMESSAGE2.nested_types = {}
TESTMESSAGE2.enum_types = {}
TESTMESSAGE2.fields = {TESTMESSAGE2_ID_FIELD, TESTMESSAGE2_BUFF_FIELD}
TESTMESSAGE2.is_extendable = false
TESTMESSAGE2.extensions = {}

TestMessage = protobuf.Message(TESTMESSAGE)
TestMessage2 = protobuf.Message(TESTMESSAGE2)

