# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_client.proto',
  package='message_client',
  serialized_pb=_b('\n\x14message_client.proto\x12\x0emessage_client\x1a\x14message_common.proto\"\'\n\x0bTestMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x62uff\x18\x02 \x01(\x0c\"(\n\x0cTestMessage2\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x62uff\x18\x02 \x01(\x0c')
  ,
  dependencies=[message_common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TESTMESSAGE = _descriptor.Descriptor(
  name='TestMessage',
  full_name='message_client.TestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='message_client.TestMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buff', full_name='message_client.TestMessage.buff', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=101,
)


_TESTMESSAGE2 = _descriptor.Descriptor(
  name='TestMessage2',
  full_name='message_client.TestMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='message_client.TestMessage2.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buff', full_name='message_client.TestMessage2.buff', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['TestMessage'] = _TESTMESSAGE
DESCRIPTOR.message_types_by_name['TestMessage2'] = _TESTMESSAGE2

TestMessage = _reflection.GeneratedProtocolMessageType('TestMessage', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE,
  __module__ = 'message_client_pb2'
  # @@protoc_insertion_point(class_scope:message_client.TestMessage)
  ))
_sym_db.RegisterMessage(TestMessage)

TestMessage2 = _reflection.GeneratedProtocolMessageType('TestMessage2', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE2,
  __module__ = 'message_client_pb2'
  # @@protoc_insertion_point(class_scope:message_client.TestMessage2)
  ))
_sym_db.RegisterMessage(TestMessage2)


# @@protoc_insertion_point(module_scope)
